### ISSUE TITLE
Copy Items tool malfunction

### ISSUE THREAD

**Issue by bzizzamia** [EsriPS/arcgis-assistant-feedback#5]
Hello!
I've been a big fan of the previous release of ArcGIS Assistant tool and I have already used the new. But today when I was writing a transfer protocol, the Copy Items tool does not seem to work. The page goes blank and does not recover. I tried accessing the tool from various accounts and browsers with no luck. I've tried selecting one or multiple items and different item types. The URL changes to: https://assistant.esri-ps.com/content?queryScope=USER&num=20&start=1&sortField=modified&sortOrder=desc&folder=allmycontent
and the rest of the page goes blank. Something I'm doing wrong or is there something going on today? Thanks for the help!!
Beth
![error](https://user-images.githubusercontent.com/63598650/116739907-3ef62380-a9c2-11eb-96bb-2379a813e990.JPG)

**Comment by thollingshead** [comment]
Hi @bzizzamia, thanks for reporting! It looks like this is a new bug in today's release. I'm also seeing the blank screen when clicking the 'Copy Items' button above the table.

The good news is there appears to be a workaround until this issue is fixed. You can still access the tool through expanding the individual item's actions menu (click the ellipses for the item, highlighted below).

![image](https://user-images.githubusercontent.com/5472848/116765041-88556b80-a9e0-11eb-9d27-7e88d8d713de.png)

**Comment by jpeterson** [comment]
Hey @bzizzamia, this issue should be resolved as of a few minutes ago. Please let us know if you're able to copy items as expected now.

**Comment by jpeterson** [comment]
Closing this issues for now, please feel free to reopen if the issue persists!

**Comment by bzizzamia** [comment]
Hello! I am able to use the Copy Items button now. Thanks!
Beth
