### ISSUE TITLE
App loading config error in Experience Builder Apps in 8.1

### ISSUE THREAD

**Issue by NabinPaudel** [EsriPS/arcgis-assistant-feedback#50]
**Describe the bug**
load app config error
Migration between portal, giving error on JSON Config file path

**To Reproduce**
1. Copy to Experience builder to destination portal
2. Open the Experience builder in destination portal
3. Open developer tools to find the error 
![image](https://user-images.githubusercontent.com/7153359/174529579-9ac795d6-429f-4e18-a2a9-adeccf478199.png)

**Comment by jpeterson** [comment]
Hi, @NabinPaudel, thanks for logging this issue!

The error you are encountering is most likely due to one of two things:

1. Assistant [failed to update the item's `url` property in the Item Description](https://guide.assistant.esri-ps.com/docs/working-with-items#applications-storymaps-web-experiences-instant-apps-etc). You can check if this is the case by opening your **new item** in ArcGIS Assistant and viewing the [Item Description](https://guide.assistant.esri-ps.com/docs/working-with-items#item-description). If the `url` property was not properly updated (i.e., to your destination portal), then you can edit it using Assistant.

2. If (1) is not the culprit (or if you resolve (1) and still see issues), then your Web Experience may have been referencing items in your origin portal by their ID or URL. Note that ArcGIS Assistant **does not** copy dependencies of items. This means, for example, if your Web Experience referenced items in your origin portal, you need to copy those items into your destination portal, then edit your Web Experience [Item Data](https://guide.assistant.esri-ps.com/docs/working-with-items#item-data) to point to the new IDs or URLs.

Let us know if this helps!
