### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mchibok** [EsriPS/arcgis-assistant-feedback#72]
On the [homepage](https://assistant.esri-ps.com/signin), I click on "Sign in with ArcGIS Online". Then I get to the esri connection box in which I enter the same credentials I use for arcgis.com. Then I click on the connect button and it brings me back to the homepage.

Tried with Chrome and Firefox, both up to date.

**Comment by jpeterson** [comment]
Hey @mchibok, thanks for reporting. Could you please check your browser's developer tools to see if anything is being logged to the console, and share that here? You might need to [persist messages across page loads](https://developer.chrome.com/docs/devtools/console/reference/#persist).

**Comment by mchibok** [comment]
Hi,

Here is the log when I try to connect. Seems to be an OAuth error.
<img width="800" alt="image" src="https://github.com/EsriPS/arcgis-assistant-feedback/assets/25492081/4efa2e07-412c-4c3b-a168-d3736ddf2e21">

**Comment by brandonlammey** [comment]
Hello @mchibok, thanks for that screenshot. Could you also try test logging in using a Chrome Incognito tab as well and share the logged console messages here as well?

**Comment by mchibok** [comment]
Hi,
Same messages in incognito mode:
![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/25492081/993a1298-7ed9-467f-99a8-1eb767399c38)

Here is the expanded User Session Error:
![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/25492081/9f16e842-8b79-4f1e-baf9-1a7985e231c0)

**Comment by J-Guenther** [comment]
Hi, we have the same problem. I can log in to the Assistant ( https://ago-assistant.esri.com/ ) by using my private ESRI Account but I can't log in using our companie's Account (our AGOL administrator). 

We have the exact same behaviour as described in the initial post. We've tried it with Firefox and Chrome (including incognito mode). Other than the previous posters, we don't get any errors in the console or network traffic overview. The authentication window just closes and nothing happens. We tried to set a breakpoint to the close event of the window but there are still no errors showing.

Edit:
If we try to log in the newer Assistant ( https://assistant.esri-ps.com/ ) we also get this:

![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/16701537/a58d7127-15d2-42f0-8229-03fa767c1d17)


One thing we also noticed:
When we try to log in to our AGOL Account using the AGOL Python API, we get an error and the authentication failed. The token seems to be missing. We are wondering if these behaviours are related to each other because the issue is very similar

**Comment by GaryPrior** [comment]
**We also have the exact same behavior as described in the initial post. Seems to have started about a month ago.  Tried it with Firefox, Edge and Chrome (including incognito mode). Same results in both Beta Assistant ( https://assistant.esri-ps.com/ ) and older https://ago-assistant.esri.com/#.** 

Chrome session console messages:
![image](https://github.com/EsriPS/arcgis-assistant-feedback/assets/25939528/1a28c4e0-8651-4751-b9b1-2d7c55af2ceb)

**To me this warning message before each error seems to be a smoking clue:
"It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour."
With each attempt to sign into ArcGIS Online amid the redirects we can see "Error" flash in the URL, but too quick to capture.
We really miss this code assistant utility. Please help! Thank you**

**Comment by J-Guenther** [comment]
Hi, we solved the issue in our case.

We had a misconfiguration in ArcGIS Online that prevented access from third party apps.

Organization->Settings->Security->Apps

We disabled "**Members can only sign in to external apps that are approved**". Now it works for us. We don't know how to approve the assistant though. So we can't add it as a single exception. But I guess that's another problem.

Can anyone else confirm that this setting caused the issue?

**Comment by mchibok** [comment]
I'll have to ask the person who is Admin for my organization, I don't see the Settings tab in Organization. I'll report back!

**Comment by GaryPrior** [comment]
**J-Guenther: Thank you! I am confirming that the ArcGIS Online "Members can only sign in to external apps that are approved" when set to Off allows us to access the Assistant tool in both the older and newer Beta apps.** At this point I'm going to assume we don't need to approve the Assistant, but we may eventually find otherwise. But we're happy campers for now!

**Comment by jpeterson** [comment]
> Hi, we solved the issue in our case.
> 
> We had a misconfiguration in ArcGIS Online that prevented access from third party apps.
> 
> Organization->Settings->Security->Apps
> 
> We disabled "**Members can only sign in to external apps that are approved**". Now it works for us. We don't know how to approve the assistant though. So we can't add it as a single exception. But I guess that's another problem.
> 
> Can anyone else confirm that this setting caused the issue?

@J-Guenther thank you for sharing! Hopefully this was the issue for anyone else running into sign-in issues with ArcGIS Online.

### For anyone finding this issue in the future: 

Enabling the "Members can only sign in to external apps that are approved" option in your ArcGIS Online organization will prevent Assistant from allowing you to login as a member of that organization. If you're having trouble logging in to Assistant and this option is enabled, disabling it should resolve the problem. 

You can learn more about this option here: [Configure security settings – Approve apps](https://doc.arcgis.com/en/arcgis-online/administer/configure-security.htm#ESRI_SECTION2_E52C6323B80341BABA3426B305832ECB)

If you wish to keep the Approved Apps option enabled, you can work around this issue by essentially treating ArcGIS Online as ArcGIS Enterprise. You can find more info in the Assistant guide here: [Sign in to ArcGIS Enterprise](https://guide.assistant.esri-ps.com/docs/working-with-accounts#sign-in-to-arcgis-enterprise). 

Here are the steps, for reference:

1. Create a new web mapping application in your organization and add `https://assistant.esri-ps.com` as a Redirect URL. Note the Client ID.
2. [Add your new item as an Approved App](https://doc.arcgis.com/en/arcgis-online/administer/configure-security.htm#ESRI_SECTION2_E52C6323B80341BABA3426B305832ECB)
3. Login to ArcGIS Assistant using the **Sign in with ArcGIS Enterprise** workflow, using the following:
    URL: `https://<org>.maps.arcgis.com`
    App ID: `<Client ID noted in step 1>`
